# Generated by Django 2.1.2 on 2018-10-12 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_user_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
