# Generated by Django 2.1.2 on 2018-10-12 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20181012_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
