# Generated by Django 2.1.2 on 2018-10-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20181012_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
