# Generated by Django 2.1.2 on 2018-10-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20181012_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='useragent',
            field=models.CharField(max_length=255),
        ),
    ]
